// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_ngRGI46PxF4hx212-dtKuLvVPvofIo',
    appId: '1:849549790181:android:4df0179b966421c5c1fd0c',
    messagingSenderId: '849549790181',
    projectId: 'mlsc-app',
    databaseURL: 'https://mlsc-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlsc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAkgeFZTCkBAIAXbmWBP1BRYiKH3KNHB0',
    appId: '1:849549790181:ios:1b4f15daba0adb4ac1fd0c',
    messagingSenderId: '849549790181',
    projectId: 'mlsc-app',
    databaseURL: 'https://mlsc-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlsc-app.appspot.com',
    androidClientId: '849549790181-0fce8clv7rl4k4bfpsicfao5kri72s3s.apps.googleusercontent.com',
    iosClientId: '849549790181-l11b3k79vg2o0apc9cd87cgn4e6irdcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeathon5App',
  );
}
