// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9lhXnRUUmOMTO7lbPQv5S5-94-mpL2o',
    appId: '1:962819408926:web:16e5c912ff20cbbe181a0f',
    messagingSenderId: '962819408926',
    projectId: 'make5app-dummy',
    authDomain: 'make5app-dummy.firebaseapp.com',
    databaseURL: 'https://make5app-dummy-default-rtdb.firebaseio.com',
    storageBucket: 'make5app-dummy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMF4heZmdjWorNFjCLIXayNr1huxT9oYo',
    appId: '1:962819408926:android:a1caa900faced3a2181a0f',
    messagingSenderId: '962819408926',
    projectId: 'make5app-dummy',
    databaseURL: 'https://make5app-dummy-default-rtdb.firebaseio.com',
    storageBucket: 'make5app-dummy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnoj4d1fj60hVPmxe9JOMbY2egID3Kl4',
    appId: '1:962819408926:ios:c4d8255eee42004c181a0f',
    messagingSenderId: '962819408926',
    projectId: 'make5app-dummy',
    databaseURL: 'https://make5app-dummy-default-rtdb.firebaseio.com',
    storageBucket: 'make5app-dummy.appspot.com',
    iosClientId: '962819408926-fjvgqgmjj1n1rfjshk4dq1crfdqmrh7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeathon5App',
  );
}
